# Generated by Django 4.2 on 2026-01-30 07:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(help_text='Bank IFSC code prefix', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance')], default='active', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role__role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='17:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='queueapp.bank')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role__role': 'branch_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['bank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_busy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='queueapp.branch')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role__role': 'counter_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counters',
                'ordering': ['branch', 'counter_id'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('average_service_time', models.IntegerField(default=5, help_text='In minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_wait_time', models.IntegerField(default=0, help_text='In minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queueapp.counter')),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queues',
                'ordering': ['counter', 'service'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('deposits', 'Deposits'), ('withdrawals', 'Withdrawals'), ('loans', 'Loan Services'), ('account_opening', 'Account Opening'), ('account_maintenance', 'Account Maintenance'), ('cash_counter', 'Cash Counter'), ('general_inquiry', 'General Inquiry'), ('foreign_exchange', 'Foreign Exchange')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('average_service_time', models.IntegerField(default=5, help_text='Estimated service time in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('is_active', models.BooleanField(default=True)),
                ('requires_appointment', models.BooleanField(default=False)),
                ('max_queue_size', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('max_capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('current_bookings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('partially_booked', 'Partially Booked'), ('fully_booked', 'Fully Booked'), ('closed', 'Closed')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='queueapp.counter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='queueapp.service')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['slot_date', 'slot_start_time'],
            },
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='queueapp.service')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='queueapp.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slot Booking',
                'verbose_name_plural': 'Slot Bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff Member'), ('counter_manager', 'Counter Manager'), ('branch_manager', 'Branch Manager'), ('admin', 'Administrator')], default='customer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Being Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='generated', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Normal'), (2, 'Senior Citizen/PWD'), (3, 'VIP'), (4, 'Emergency')], default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('service_ended_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_time', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('waiting_time', models.IntegerField(blank=True, help_text='Actual wait time in minutes', null=True)),
                ('service_duration', models.IntegerField(blank=True, help_text='Service duration in minutes', null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('skip_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='queueapp.counter')),
                ('customer', models.ForeignKey(limit_choices_to={'role__role': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='queueapp.queue')),
                ('served_by', models.ForeignKey(blank=True, limit_choices_to={'role__role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_tokens', to=settings.AUTH_USER_MODEL)),
                ('slot_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token', to='queueapp.slotbooking')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_tokens', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('served_tokens', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cancelled_tokens', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('no_show_tokens', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_wait_time', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('avg_service_time', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('peak_hour', models.IntegerField(blank=True, help_text='Hour of day 0-23', null=True)),
                ('max_queue_length', models.IntegerField(default=0, help_text='Peak queue length')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='queueapp.queue')),
            ],
            options={
                'verbose_name': 'Queue Analytics',
                'verbose_name_plural': 'Queue Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queueapp.service'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('token_called', 'Token Called'), ('token_confirmed', 'Token Confirmed'), ('slot_reminder', 'Slot Reminder'), ('queue_update', 'Queue Update'), ('system_alert', 'System Alert'), ('service_alert', 'Service Alert'), ('booking_confirmation', 'Booking Confirmation')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='queueapp.slotbooking')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='queueapp.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='counter',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='queueapp.service'),
        ),
        migrations.AddField(
            model_name='counter',
            name='staff_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('token_generated', 'Token Generated'), ('token_called', 'Token Called'), ('token_served', 'Token Served'), ('booking_created', 'Booking Created'), ('booking_cancelled', 'Booking Cancelled'), ('counter_activated', 'Counter Activated'), ('counter_deactivated', 'Counter Deactivated'), ('staff_assigned', 'Staff Assigned'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='queueapp.slotbooking')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='queueapp.token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='queueapp_us_role_23c897_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['status', 'queue'], name='queueapp_to_status_b28cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['customer', 'status'], name='queueapp_to_custome_071b86_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['generated_at'], name='queueapp_to_generat_129965_idx'),
        ),
        migrations.AddIndex(
            model_name='slotbooking',
            index=models.Index(fields=['user', 'status'], name='queueapp_sl_user_id_2a04df_idx'),
        ),
        migrations.AddIndex(
            model_name='slotbooking',
            index=models.Index(fields=['slot', 'status'], name='queueapp_sl_slot_id_11cddf_idx'),
        ),
        migrations.AddIndex(
            model_name='slotbooking',
            index=models.Index(fields=['booking_date'], name='queueapp_sl_booking_c48d45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slotbooking',
            unique_together={('user', 'slot')},
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['slot_date', 'status'], name='queueapp_sl_slot_da_e4d9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['counter', 'slot_date'], name='queueapp_sl_counter_993965_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('counter', 'slot_date', 'slot_start_time')},
        ),
        migrations.AddIndex(
            model_name='queueanalytics',
            index=models.Index(fields=['date'], name='queueapp_qu_date_7ad0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='queueanalytics',
            index=models.Index(fields=['queue', 'date'], name='queueapp_qu_queue_i_68ae8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queueanalytics',
            unique_together={('date', 'queue')},
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('counter', 'service')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='queueapp_no_user_id_16aba8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='queueapp_no_created_c0ebec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='counter',
            unique_together={('branch', 'counter_id')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('bank', 'branch_code')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'created_at'], name='queueapp_au_action__7342ee_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='queueapp_au_user_id_644f16_idx'),
        ),
    ]
