# Generated by Django 4.2 on 2026-01-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0002_fix_models'),
    ]

    operations = [
    ]
