# Generated by Django 4.2 on 2026-01-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0003_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueanalytics',
            name='date',
            field=models.DateField(),
        ),
    ]
